<a href="https://colab.research.google.com/github/yuhui-0611/ESAA/blob/main/ESAA_YB_WEEK1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

머신러닝의 개념
- 앱을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 일정한 패턴을 찾기 어려운 경우 사용
- 데이터 기반 통계적 신뢰도 강화 및 예측 오류 최소화
- 패턴 학습 및 예측 수행을 통한 정확한 예측 및 의사결정 도출

머신러닝의 분류
- 지도학습 : 분류, 회귀, 추천 시스템, 시각/음성감지, 텍스트분석, NLP
- 비지도학습 : 클러스터링, 차원축소, 강화학습

# **넘파이**

- Numerical Python : 파이썬에서 선형대수 기반 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
- 루프를 사용하지 않고 대량의 데이터 배열 연산을 가능케 함 > 빠른 속도 보장

**넘파이 ndarray 개요**

In [ ]:
import numpy as np

- import numpy만 해도 충분하지만, as np를 추가해 약어로 모듈 표현
- 넘파이 기반 데이터 타입 = ndarray
- ndarray를 이용해 다차원 배열 쉽게 생성 & 다양한 연산 수행 가능
- 넘파이 array() 함수 : 리스트와 같은 다양한 인자 입력받은 후 ndarray로 변환
- 생성된 ndarray 배열의 shape 변수 : ndarray의 행렬 수를 튜플 형태로 지니며, 이를 통해 ndarray 배열의 차원까지 알 수 있음

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type：', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type：', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type：', type(array3))
print('array3 array 형태:', array3.shape)

array1 type： <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type： <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type： <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
## output
# array1 type： <class 'numpy.ndarray'>
# array1 array 형태: (3,)
# array2 type： <class 'numpy.ndarray'>
# array2 array 형태: (2, 3)
# array3 type： <class 'numpy.ndarray'>
# array3 array 형태: (1, 3)

- np.array() : nparray로 변환을 원하는 객체를 인자로 입력하면, nparray 반환
- nparray.shape = nparray의 차원과 크기를 튜플 형태로 나타냄
- ex) [1,2,3]인 array1 shape = 1차원 데이터 & 3개의 데이터
    [[1,2,3], [2,3,4]]인 array2 shape =  2차원 array & 행 2개, 열 3개 & 크기 6

In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'. format(array1.ndim,
                                                            array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


In [ ]:
## output
# array1: 1차원, array2: 2차원, array3: 2차원

- array() 함수의 인자로는 파이썬의 리스트가 주로 사용됨
- 리스트의 [] = 1차원, [[]] = 2차원

**ndarray의 데이터 타입**

- ndarray내의 데이터 값은 숫자, 문자열, 불 등 모두 가능
- ndarray 내 데이터 타입은 같은 데이터 타입만 가능
- 즉, 한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음
- ndarray내의 데이터 타입은 dtype으로 확인 가능

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
## output
# <class 'list'>
# <class 'numpy.ndarray'>
# [1 2 3] int64

- list를 array로 바꾸었고, 이렇게 변경된 ndarray 내 데이터 값은 모두 int64형임
- list는 서로 다른 데이터 타입을 가질 수 있지만, ndarray는 연산 특성상 같은 데이터 타입만 가질 수 있음
- 하지만, 만약 다른 데이터 유형이 섞인 list를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용

In [ ]:
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
## output
# ['1' '2' 'test'] <U21
# [1. 2. 3.] float64

- 첫번째 결과: int형 값과 문자열이 섞인 list2를 ndarray로 변환한 ndarray2는 숫자형 값 1,2가 모두 문자열로 변환됨
- 두번째 결과: int형과 float형이 섞인 list3도 int1,2가 모두 실수인 float64로 변환됨

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1 ])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
## output
# [1. 2. 3.] float64
# [1 2 3] int32
# [1 2 3] int32

- astype() = ndarray내 데이터 값 타입 변경
- 대용량 데이터의 ndarray를 만들 때 메모리 절약 가능
- 예를 들어, int형으로 충분한데 데이터 타입이 float라면 int형으로 바꾸어 메모리 절약 가능
- 위 코드: int32형 데이터를 float64로 변환하고 다시 int32로 변경한 것

**ndarray를 편리하게 생성하기 - arange, zeros, ones**

- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화하는 경우 사용

***arrange()*** : range()와 유사하며, 0부터 '함수 인자 값 -1'까지의 값을 순차적으로 ndarray의 데이터 값으로 변환

In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
## output
# [0 1 2 3 4 5 6 7 8 9]
# int64 (10,)

- default 함수 인자는 stop 값
- 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray가 만들어짐
- 위 코드는 stop 값만 부여했으나, range처럼 start 값도 부여할 수 있음

***zeros()*** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray 반환

***ones()*** : 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환
- 함수 인자로 dtype를 정해주지 않으면, default로 float64형의 데이터로 ndarray 채움

In [ ]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
## output
# [[0 0]
#  [0 0]
#  [0 0]]
# int32 (3, 2)
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]
# float64 (3, 2)

**ndarray의 차원과 크기를 변경하는 reshape()**

reshape() : ndarray를 특정 차원 및 크기로 변환
- 변환을 원하는 크기를 함수 인자로 부여

In [ ]:
array1 = np.arange(10)
print('array1：\n', array1)

array2 = array1.reshape(2, 5)
print('array2：\n', array2)

array3 = array1.reshape(5, 2)
print('array3：\n', array3)

array1：
 [0 1 2 3 4 5 6 7 8 9]
array2：
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3：
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
## output
# array1：
#  [0 1 2 3 4 5 6 7 8 9]
# array2：
#  [[0 1 2 3 4]
#  [5 6 7 8 9]]
# array3：
#  [[0 1]
#  [2 3]
#  [4 5]
#  [6 7]
#  [8 9]]

- 0~9까지의 1차원 ndarray를 2행 5열과 5행 2열 형태로 2차원 ndarray로 변환

In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

- 위 코드처럼 지정된 사이즈 변경이 불가하면 오류 발생
- ex. (10,)인 1차원 10행 데이터를 (4,3) shape 형태로 변경 불가

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape：', array2.shape)

arrays = array1.reshape(5, -1)
print('array3 shape：', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape： (2, 5)
array3 shape： (5, 2)


- -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환
- array은 1차원 ndarray로 0~9까지의 데이터를 가지고 있음
- array1.reshape(-1,5) : array1과 호환될 수 있는 2차원 ndarray로 변환하되, 고정된 5개의 칼럼에 맞는 행을 자동으로 새롭게 생성해 변환
- 즉, 5열로 만들려면 행은 2개여야 하므로 2x5의 2차원 ndarray로 변환
- array1.reshape(5,-1) : 5개의 행에 맞는 열로 변환
- 물론 -1을 사용하더라도 호환 불가능한 형태는 변환 불가

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d：\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5：\n', array5.tolist())
print('array5 shape：', array5.shape)

# 1 차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6：\n', array6.tolist())
print('array6 shape：', array6.shape)

array3d：
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape： (8, 1)
array6：
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape： (8, 1)


In [ ]:
## output
# array3d：
#  [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
# array5：
#  [[0], [1], [2], [3], [4], [5], [6], [7]]
# array5 shape： (8, 1)
# array6：
#  [[0], [1], [2], [3], [4], [5], [6], [7]]
# array6 shape： (8, 1)

- -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용됨
- reshape(-1,1) : 원본 ndarray가 어떤 형태라도 2차원이고, 여러행을 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환시킴
- tolist() : 리스트 자료형으로 변환 가능

**넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱**

1.   특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치 데이터 반환
2.   슬라이싱 : 연속된 인덱스상의 ndarray 추출, ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작에서 종료-1까지의 위치에 있는 데이터의 ndarray 반환
3.   팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환
4.   불린 인덱식 : 특정 조건에 해당하는지 여부인 T/F 값 인덱싱 집합을 기반으로 T에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환



```
단일 값 추출
```



In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1：', array1)

# index는 0부터 시작하므로 arrayl[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value：', value)
print(type(value))

print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1： [1 2 3 4 5 6 7 8 9]
value： 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
## output
# array1： [1 2 3 4 5 6 7 8 9]
# value： 3
# <class 'numpy.int64'>
# 맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8

- 인덱스는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터 값을 의미하므로 데이터값 3을 의미
- array1[2]의 타입은 더이상 ndarray 타입이 아니고 ndarray 내의 데이터 값을 의미
- 인덱스 -1은 맨 뒤의 값, -2는 뒤에서 두번째 값

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1：', array1)

array1： [9 2 3 4 5 6 7 8 0]


In [ ]:
## output
# array1： [9 2 3 4 5 6 7 8 0]

위 코드처럼 단일 인덱스를 이용해 ndarray 내 데이터 값도 간단히 수정 가능

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1 ])
print('row=1, col=O) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
row=1, col=O) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [ ]:
## output
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# (row=0, col=0) index 가리키는 값: 1
# (row=0, col=1) index 가리키는 값: 2
# row=1, col=O) index 가리키는 값: 4
# (row=2, col=2) index 가리키는 값: 9

- 3개의 행열 각각이 0,1,2의 인덱스로 구성되어 있음
- 2차원에서 : axis0, axis1로 구분 (행,열)
- 3차원에서 : axis0, axis1, axis2의 3개의 축으로 구분 (행,열,높이)
- 이런 식으로 넘파이의 다차원 ndarray는 axis 구분을 가짐
- 더해, 축 기반 연산에서 axis가 생략되면 axis0을 의미



```
슬라이싱
```



단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 덱싱으로 추출된 데이터 세트는 모두 ndarray 타입

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
## output
# [1 2 3]
# <class 'numpy.ndarray'>

1.   ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2.   ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
3.   ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
## output
# [1 2 3]
# [4 5 6 7 8 9]
# [1 2 3 4 5 6 7 8 9]

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print ('array 2d :\n)', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array 2d :
) [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
## output
# array 2d :
# ) [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# array2d[0:2, 0:2]
#  [[1 2]
#  [4 5]]
# array2d[1:3, 0:3]
#  [[4 5 6]
#  [7 8 9]]
# array2d[1:3, :]
#  [[4 5 6]
#  [7 8 9]]
# array2d[:, :]
#  [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
# array2d[:2, 1:]
#  [[2 3]
#  [5 6]]
# array2d[:2, 0]
#  [1 4]

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape：', array2d[0].shape, 'array2d[1] shape：', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape： (3,) array2d[1] shape： (3,)


In [ ]:
## output
# [1 2 3]
# [4 5 6]
# array2d[0] shape： (3,) array2d[1] shape： (3,)

-  2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환
- 즉, array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면 행 축(axis 0)의 첫 번째 로우 ndarray를 반환하며 반환된 ndarray = 1차원
- 3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray 반환



```
팬시 인덱싱
```



리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0：2] => ', array4.tolist())

array5 = array2d[[0, 1 ]]
print('array2d[[0, 1 ]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0：2] =>  [[1, 2], [4, 5]]
array2d[[0, 1 ]] => [[1, 2, 3], [4, 5, 6]]


In [ ]:
## output
# array2d[[0, 1], 2] => [3, 6]
# array2d[[0, 1], 0：2] =>  [[1, 2], [4, 5]]
# array2d[[0, 1 ]] => [[1, 2, 3], [4, 5, 6]]

- array2d[[0,1], 2] 로우 축에 팬시 인덱싱인 [0,1]을, 칼럼 축에는 단일 값 인덱싱 2를 적용
-  (row, col) 인덱스가(0,2), (1,2)로 적용돼 [3, 6]을 반환
-  array2d[[0,1], 0:2]는 ((0,0), (0,1)), ((1,0), (1,1)) 인덱싱이 적용돼 [[1,2], [4,5]]를 반환
- array2d[[0,1]]는 ((0, :), (1, :)) 인덱싱이 적용돼 [[1,2,3], [4,5,6]]을 반환



```
불린 인덱싱
```



조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용

In [ ]:
array1d = np.arange(start=1, stop=10)

# [ ] 안에 array 1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array 1d > 5 불린 인덱싱 결과 값 :', array3)

array 1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [ ]:
## output
# array 1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]

In [ ]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
## output
# array([False, False, False, False, False, True, True, True, True])

- 5 보다 큰 데이터가 있는 위치는True 값이, 그렇지 않는 경우는 False 값이 반환됨을 확인할 수 있음
- 조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 [ ] 내에 입력하면 False 값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환
-  즉, array([False, False, False, False, False, True, True, True, True]) 에서 False가 있는 인덱스 0 〜 4는 무시하고 인덱스 [5,6,7,8]이 만들어지고 이 위치 인덱스에 해당하는 데이터 세트 [6, 7, 8, 9]를 반환

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 ：', array3)

불린 인덱스로 필터링 결과 ： [6 7 8 9]


In [ ]:
## output
# 불린 인덱스로 필터링 결과 ： [6 7 8 9]

In [ ]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [ ]:
## output
# 일반 인덱스로 필터링 결과 : [6 7 8 9]

- Step 1 : array1d > 5와 같이 ndarray의 필터링 조건을 [ ] 안에 기재
- Step 2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장 (유의해야 할 사항은 True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장한다는 것)
- Step 3 : 저장된 인덱스 데이터 세트로 ndarray 조회

**행렬의 정렬 - sort()와 argsort()**

- np.sort() : 넘파이에서 sort() 호출 -> 원 행렬 그대로 유지한 채 원 행렬의 정렬된 행렬 반환
- ndarray.sort() : 행렬 자체에서 sort() 호출 -> 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [ ]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [ ]:
## output
# 원본 행렬: [3 1 9 5]
# np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
# np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
# org_array.sort( ) 호출 후 반환된 행렬: None
# org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]

- 원본 행렬 [3 1 9 5]에 대해서 np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환
- ndarray.sort()는 원본 행렬 자체를 정렬한 값으로 변환

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
## output
# 내림차순으로 정렬: [9 5 3 1]

 - np.sort()나 ndarray. sort( ) 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬
 - 내림차순으로 정렬하기 위해서는 [::-1]을 적용 -> np.sort( )[::-1]과 같이 사용

In [ ]:
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [ ]:
## output
# 로우 방향으로 정렬:
#  [[ 7  1]
#  [ 8 12]]
# 칼럼 방향으로 정렬:
#  [[ 8 12]
#  [ 1  7]]

행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행 가능

In [ ]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [ ]:
## output
# <class 'numpy.ndarray'>
# 행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]

- 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용
- np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
## output
# 행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]

오름차순이 아닌 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도 np.argsort( )[::-1]과 같이 [::-1]을 적용

In [ ]:
import numpy as np

name_array = np.array(['John1', 'Mike','Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John1' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [ ]:
## output
# 성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
# 성적 오름차순으로 name_array의 이름 출력: ['John1' 'Sarah' 'Samuel' 'Mike' 'Kate']

- 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 뒤에 소개할 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없음
- 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 함
- 예를 들어 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 각각 ndarray로 가져야 함
- 즉 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 활용하고자 한다면, name_array=['John', 'Mike', 'Sarah1', 'Kate', ‘Samuel']와 score_array=[78,95,84,98,88]과 같이 2개의 ndarray를 만들어야 함
- 이때 시험 성적순으로 학생 이름을 출력하고자 한다면, np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있으며, 이러한 방식은 넘파이의 데이터 추출에서 많이 사용됨

**선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

***행렬 내적 (행렬 곱)***

두 행렬 A와 B의 내적은 np.dot()을 이용해 계산 가능

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [ ]:
## output
# 행렬 내적 결과:
# [[ 58  64]
# [139 154]]

***전치 행렬***

- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
- 즉 2x2 행렬 A가 있을 경우 A 행렬의 1행 2열의 원소를 2행 1열의 원소로, 2행 1 열의 원소를 1행 2열의 원소로 교환하는 것
- A^t

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A 의 전치 행렬:\n', transpose_mat)

A 의 전치 행렬:
 [[1 3]
 [2 4]]


In [ ]:
## output
# A 의 전치 행렬:
#  [[1 3]
#  [2 4]]