<a href="https://colab.research.google.com/github/yuhui-0611/ESAA/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
# numpy 패키지 버전 문자열로 반환
np.show_config()
# numpy가 설치된 환경의 빌드/설정 정보 출력

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print('memory size of array:', array.nbytes)

memory size of array: 40


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector_10 = np.zeros(10)
null_vector_10[4] = 1
print(null_vector_10)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
vector_reverse = vector[::-1]
print(vector_reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(0, 9)
matrix = matrix.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
A = np.array([1,2,0,0,4,0])
B = (A != 0)
print(B)
print(len(A))
print(np.arange(len(A)))
indices = np.arange(len(A))[B]
print(indices)

[ True  True False False  True False]
6
[0 1 2 3 4 5]
[0 1 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
identity = np.identity(3)
eye = np.eye(3)
print(identity)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array_r = np.random.random((3, 3, 3))
# np.random.random(shape) : 각 원소는 0 이상 1 미만 구간의 분포에서 무작위 값을 가짐
print(array_r)

[[[0.90987638 0.1559286  0.67481881]
  [0.52848906 0.55917184 0.49304359]
  [0.3152211  0.65536263 0.48528848]]

 [[0.52274441 0.17077544 0.76185564]
  [0.97550072 0.20564902 0.48308468]
  [0.317222   0.06084081 0.81461824]]

 [[0.22883482 0.40889146 0.3363348 ]
  [0.09995954 0.66910959 0.21246516]
  [0.10560018 0.29581456 0.75820211]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array_mn = np.random.random((10, 10))
print(array_mn, '\n')

min = np.min(array_mn)
max = np.max(array_mn)
print('min:', min, '\nmax:', max)

[[6.27602355e-01 3.63768288e-01 9.56457012e-01 2.78367801e-01
  8.35867162e-01 2.85308781e-01 4.07922129e-01 5.99385079e-02
  2.90353112e-01 5.64481782e-01]
 [9.53918001e-01 8.82289603e-01 4.83885719e-01 6.65444149e-01
  5.24959868e-01 9.08054454e-01 7.19817942e-01 5.64395037e-02
  9.13784578e-01 1.61365408e-01]
 [9.02381759e-01 6.83450930e-01 7.06560443e-01 6.90055764e-01
  6.66298124e-02 8.57590472e-01 3.84192389e-02 7.76673512e-01
  7.16716681e-01 4.73748311e-01]
 [9.47726088e-02 2.95995760e-01 5.84455340e-01 7.76037050e-01
  8.95124588e-01 1.65169394e-01 1.07186788e-01 4.89768395e-01
  4.01612963e-02 3.24820737e-01]
 [5.20508601e-01 3.64843965e-01 9.40756408e-01 1.23362902e-01
  2.65004364e-01 9.20075101e-01 8.90516187e-01 8.79591609e-01
  2.49507674e-02 4.66046958e-01]
 [3.19042529e-01 4.84319386e-01 8.11996297e-01 6.32266904e-01
  2.65286227e-01 5.60930704e-01 1.21380835e-02 7.37859697e-01
  5.19743634e-01 2.60394100e-01]
 [6.17973575e-02 6.21037763e-01 4.60292746e-01 1.97277602e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array_mean = np.random.random(30)
mean = np.mean(array_mean)
print(array_mean)
print('mean: ', mean)

[0.10967342 0.73804688 0.7904082  0.46733414 0.2772791  0.52700133
 0.7137232  0.286757   0.41031077 0.20365354 0.19866169 0.20825109
 0.32562876 0.48286436 0.83502418 0.57673145 0.49904681 0.70204281
 0.82417633 0.0819867  0.71516803 0.13399593 0.25660054 0.01206732
 0.15164868 0.14450623 0.3065961  0.43070102 0.1329673  0.22517994]
mean:  0.39226776213521336


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array_2d = np.ones((5, 5))
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan, False, False, nan, True, True
- nan은 숫자가 아니기에 어떤 수와 곱해도 nan이 나옴
- nan은 자기 자신과도 같지 않음
- nan과의 모든 비교 연산은 False
- 집합인 set에 np.nan을 넣고 그 안에 np.nan이 있는지 확인하는 것

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
matrix_5 = np.diag([1, 2, 3, 4], k=-1)

# k=-1 : 주 대각선 바로 아래
# k=0 : 주 대각선
# k=1 : 주 대각선 바로 위

print(matrix_5)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
check = np.zeros((8, 8))
print(check)
# 먼저 0으로 채운 matrix 생성

check[1::2, 1::2] = 1
check[::2, ::2] = 1
# start : stop : step
# 1::2 = 1부터 끝까지 2칸 씩 건너뛴다는 뜻 (기본값 = 1)
print(check)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
array_678 = (6, 7, 8)
index = np.unravel_index(100, array_678)
print(np.array(index))

[1 5 4]


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
array_5 = np.random.random((5, 5))
mean = np.mean(array_5)
s = np.std(array_5)
array_5 = (array_5 - mean) / s
print(array_5)

[[ 1.14147377 -0.58071096  0.73302926  1.27809504  0.38245051]
 [ 0.11286318 -0.20922419 -1.89210724 -1.02514855  1.33713752]
 [-1.20453615 -1.00188077  0.13578958 -0.14919215  1.04626938]
 [ 1.13253998 -1.73572125  1.26888341  0.69966811  0.36350162]
 [ 0.29685283 -0.81891921 -1.4320131   0.96415259 -0.8432532 ]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
cdtype = np.dtype([('R', np.uint8),
                   ('G', np.uint8),
                   ('B', np.uint8),
                   ('A', np.uint8)])
# uint8 = unsigned 8-bit integer = u1
print(cdtype)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3

In [ ]:
# column 2


In [ ]:
# column 3
