<a href="https://colab.research.google.com/github/yuhui-0611/ESAA/blob/main/OB_0410_%EC%84%B8%EC%85%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7,7)
X, X.shape

(tensor([[0.3596, 0.3094, 0.4474, 0.1172, 0.4044, 0.5228, 0.2666],
         [0.2715, 0.2204, 0.1240, 0.3739, 0.9260, 0.5859, 0.8105],
         [0.8439, 0.1713, 0.8179, 0.6046, 0.2557, 0.6155, 0.1286],
         [0.9970, 0.0222, 0.9331, 0.6168, 0.9600, 0.8557, 0.7802],
         [0.6805, 0.4336, 0.3124, 0.6724, 0.4132, 0.5109, 0.6248],
         [0.4878, 0.8636, 0.2515, 0.7516, 0.4340, 0.2974, 0.5275],
         [0.1395, 0.1784, 0.0644, 0.8428, 0.7437, 0.0732, 0.9694]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
Y = torch.rand(1,7)

# Perform matrix multiplication
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.1231],
         [1.4179],
         [1.4525],
         [2.0400],
         [1.7274],
         [1.8920],
         [1.1557]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(7,7)
Y = torch.rand(1,7)

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)
### GPU에서도 난수가 사용되므로,
### 결과 재현성을 위해 torch.cuda.manual_seed(1234)로 GPU 랜덤 시드를 고정


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
t_A = torch.rand(size=(2,3)).to(device)
t_B = torch.rand(size=(2,3)).to(device)
print(t_A,t_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
t_C = torch.matmul(t_A, t_B.T)
print(t_C, t_C.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max = t_C.max()
print(max)

# Find min
min = t_C.min()
print(min)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
arg_max = t_C.argmax()
print(arg_max)

# Find arg min
arg_min = t_C.argmin()
print(arg_min)

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
t_D = torch.rand(1,1,1,10)

# Remove single dimensions
t_E = t_D.squeeze()
### squeeze() = 크기가 1인 차원(axis)을 제거하는 함수
### 주로 쓸데없이 붙어 있는 차원을 없애서 데이터 모양을 모델 입력이나 출력에 맞추기 위해 사용

# Print out tensors and their shapes
print(t_D, t_D.shape)
print(t_E, t_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
