<a href="https://colab.research.google.com/github/yuhui-0611/ESAA/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
A = np.random.randint(0, 10, (5, 3))
B = np.random.randint(0, 10, (3, 2))
# randint = int로 random
C = np.dot(A, B)
# 2차원일 때, np.dot(A,B) = A @ B

print("A =\n", A)
print("B =\n", B)
print("C =\n", C)

A =
 [[1 1 5]
 [9 1 0]
 [0 7 4]
 [1 8 1]
 [6 6 4]]
B =
 [[4 6]
 [9 6]
 [1 6]]
C =
 [[18 42]
 [45 60]
 [67 66]
 [77 60]
 [82 96]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array_1d = np.arange(10)
D = (array_1d >= 3) & (array_1d <= 8)
array_1d[D] *= -1
# '*=' = 곱셈 후 대입
print(array_1d)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [4]:
A = np.random.random((5,3))
print(A)

[[0.4486086  0.5686369  0.85090669]
 [0.88621934 0.88735251 0.99748095]
 [0.36533492 0.28014579 0.92808233]
 [0.28946342 0.73387485 0.46068678]
 [0.72301789 0.10563873 0.57893336]]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9, 10

- 파이썬에서 sum은 그냥 모든 수를 더하는 것이므로 10-1=9
- np.sum(a, axis=None)
- 즉, axis = -1인 것이므로 1차원이기에 행 전체를 의미

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- **는 거듭제곱 연산자
-

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

[4 1 3 2 4 6 0 9 7 9]
[4 1 1 7 3 8 7 9 9 3]
[1 3 4 7 9]


Z1: [4 5 8 8 9 8 5 9 9 7]
Z2: [6 3 7 7 0 6 0 9 2 7]
[7 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


<ipython-input-67-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

-24.5


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

[6. 7. 9. 2. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

[[1 0 1 4 4]
 [3 0 3 0 0]
 [1 4 4 3 0]
 [4 3 4 2 3]
 [1 3 2 3 3]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

[1 8 4 7 8 9 9 9 3 1]
[1 1 3 4 7 8 8 9 9 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

[4 0 1 1 2 2 6 0 9 1]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

65

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

[[0. 0. 0.]
 [0. 0. 8.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

[[1 7 3]
 [9 0 1]
 [8 6 4]]


array([[1, 7, 3],
       [8, 6, 4],
       [9, 0, 1]])

[[7 6 7]
 [7 8 4]
 [5 4 7]]


array([[5, 4, 7],
       [7, 6, 7],
       [7, 8, 4]])

[[7 9 5]
 [1 8 2]
 [6 8 1]]


array([[6, 8, 1],
       [1, 8, 2],
       [7, 9, 5]])