<a href="https://colab.research.google.com/github/yuhui-0611/ESAA/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [7]:
A = np.random.randint(0, 10, (5, 3))
B = np.random.randint(0, 10, (3, 2))
# randint = int로 random
C = np.dot(A, B)
# 2차원일 때, np.dot(A,B) = A @ B

print("A =\n", A)
print("B =\n", B)
print("C =\n", C)

A =
 [[1 1 5]
 [9 1 0]
 [0 7 4]
 [1 8 1]
 [6 6 4]]
B =
 [[4 6]
 [9 6]
 [1 6]]
C =
 [[18 42]
 [45 60]
 [67 66]
 [77 60]
 [82 96]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [9]:
array_1d = np.arange(10)
print(array_1d)

array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
# '*=' = 곱셈 후 대입
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
print(list(range(5)))
# range() = 0부터 ()안의 수만큼의 정수 시퀀스를 만듦

[0, 1, 2, 3, 4]


9, 10

- 파이썬에서 sum은 그냥 모든 수를 더하는 것이므로 10-1=9
- np.sum(a, axis=None)
- 즉, axis = -1인 것이므로 1차원이기에 열 전체를 의미

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [18]:
Z = np.arange(4).reshape(2,2)
print(Z)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# legal = print(Z<Z>Z)

[[0 1]
 [2 3]]
[[ 1  1]
 [ 4 27]]
[[0 1]
 [2 4]]
[[False False]
 [False False]]
[[0.+0.j 0.+1.j]
 [0.+2.j 0.+3.j]]
[[0. 1.]
 [2. 3.]]


- **는 거듭제곱 연산자
- A<<2 = A를 2의 거듭제곱으로 곱함, A>>2 = A를 2의 거듭제곱으로 나눔 / ex. 2<<3 = 2*2^3
- 1j = 허수 단위 i = root(-1)
- '/' = 단순 나눗셈

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
print(np.array(0) / np.array(0))
# 0/0은 정의되지 않기 때문에 nan

print(np.array(0) // np.array(0))
# '//' = 바닥 나눗셈 연산자 floor division
# ex. 7//2 => 7/2 = 3.5이고 이를 내림하면 3으로 산출됨
# np.floor_division(a,b) = a//b
# 0//0은 경고를 내고 0 반환

print(np.array([np.nan]).astype(int).astype(float))
# nan을 int로 강제 변환하면 정의가 모호해 64비트 정수의 최솟값으로 출력
# 이를 다시 float로 변환하면 그 값이 그대로 출력됨

nan
0
[-9.22337204e+18]


/tmp/ipython-input-278587233.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipython-input-278587233.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipython-input-278587233.py:10: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

common_values = np.intersect1d(Z1,Z2)
# intersect1d() = 두 값에 공통으로 들어있는 값들을 정렬된 1d 배열로 산출
# 1d로 만들 때만 intersect1d() 함수를 사용하고, 행 단위의 교집합이 필요하면, intersect_rows() 또는 tuple화해서 처리

print(Z1)
print(Z2)
print(common_values)

[0 4 9 1 0 9 4 4 7 3]
[1 2 1 9 3 1 3 5 9 4]
[1 3 4 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)
# sqrt(-1) = nan : 경고 발생, 정의역 밖이라 nan으로 산출
# emath.sqrt(-1) = 1j : 자동으로 복소수로 승격

/tmp/ipython-input-3636433676.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [38]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
# range()와 동일하게 arange()도 start는 포함하고, end 및 stop은 제외함
# dtype='datetime64[D]' : 날짜 단위로 하루씩 증가
# 달, 시간 단위로 증가하게 하려면 dtype = 'datetime64[M], dtype = 'datetime64[h]

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [60]:
A = np.arange(1,10).reshape(3,3)
print(A)
B = np.arange(11,20).reshape(3,3)
print(B)

np.multiply(np.add(A,B),np.divide(-A,2))
np.multiply(np.add(A,B),np.divide((-A),2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[  -6.,  -14.,  -24.],
       [ -36.,  -50.,  -66.],
       [ -84., -104., -126.]])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

[6. 7. 9. 2. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

[1 8 4 7 8 9 9 9 3 1]
[1 1 3 4 7 8 8 9 9 9]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

[4 0 1 1 2 2 6 0 9 1]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

65

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

[[0. 0. 0.]
 [0. 0. 8.]
 [0. 0. 8.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

[[1 7 3]
 [9 0 1]
 [8 6 4]]


array([[1, 7, 3],
       [8, 6, 4],
       [9, 0, 1]])

[[7 6 7]
 [7 8 4]
 [5 4 7]]


array([[5, 4, 7],
       [7, 6, 7],
       [7, 8, 4]])

[[7 9 5]
 [1 8 2]
 [6 8 1]]


array([[6, 8, 1],
       [1, 8, 2],
       [7, 9, 5]])